channels:
- conda-forge
dependencies:
- python=3.12
- pyiron_base=0.11.7
- qe=7.2
- qe-tools=2.0.0
- ase=3.24.0
- matplotlib=3.10.1
- xmlschema=3.4.3
- jobflow=0.1.19
- pygraphviz=1.14
- pip
- pip:
  - git+https://github.com/aiidateam/aiida-workgraph.git@898b6eb4dada8ecc551b55378e1f3799720b7c5d
