name: aiida

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: "3.12"
        environment-file: environment.yml
        auto-activate-base: false
    - name: Installation and setup
      shell: bash -l {0}
      run: |
        pip install -e adis_tools
        pip install -e python_workflow_definition
        conda install -c conda-forge jupyter papermill
        export ESPRESSO_PSEUDO=$(pwd)/espresso/pseudo
        verdi presto --profile-name adis
    # Add Upterm for SSH access
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
      # This is optional - you can make it conditional:
      if: ${{ failure() || github.event_name == 'workflow_dispatch' }}
    - name: Tests
      shell: bash -l {0}
      run: |
        export ESPRESSO_PSEUDO=$(pwd)/espresso/pseudo
        
        papermill universal_simple_to_aiida.ipynb universal_simple_to_aiida_out.ipynb -k "python3"
        papermill universal_qe_to_aiida.ipynb universal_qe_to_aiida_out.ipynb -k "python3"

        papermill aiida_to_pyiron_base_simple.ipynb aiida_to_pyiron_base_simple_out.ipynb -k "python3"
        papermill aiida_to_pyiron_base_qe.ipynb aiida_to_pyiron_base_qe_out.ipynb -k "python3"

        papermill aiida_to_jobflow_simple.ipynb aiida_to_jobflow_simple_out.ipynb -k "python3"
        papermill aiida_to_jobflow_qe.ipynb aiida_to_jobflow_qe_out.ipynb -k "python3"
